Repository YashJain2/Algorithms, pull requests merged in 2020-10, with the labels that each got.

#6 insertion sort
  Sorting/insertionsort.c
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest2020

#7 chain matrix multiply
  algo/chain_matrix/chainmatrix.cpp
  algo/chain_matrix/chainmatrix.exe
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest2020

#8 selection sort
  Sorting/selectionsort.c
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest2020

#9 bubble sort
  Sorting/bubblesort.c
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest2020

#10 Added Sorting Algorithm using Bubble Sort, Insertion Sort, Selection…
  .DS_Store
  Sorting/.DS_Store
  Sorting/Bubble_Sort.py
  Sorting/Insertion_Sort.py
  Sorting/Selection_Sort.py
Labels: hackathon, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, question

#12 Added Caesar Shift Python in algo dir
  .DS_Store
  algo/.DS_Store
  algo/Caesar shift/Encrypt_Decrypt_Text.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, question

#13 created a file for bubble sort in c++
  Sorting/bubble sort.cpp
Labels: hackathon, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#14 Added chain matrix in c and java
  algo/chain_matrix/chainmatrix.c
  algo/chain_matrix/chainmatrix.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, question

#21 Created Prim's cpp
  algo/Prim's/Prim's.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#22 Created Heapsort
  Sorting/Heap_sort
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#27 Prim's MST algo
  algo/Prim's/prim.py
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#23 Created n-queen-problem.cpp
  algo/Backtracking/n_queen_problem.cpp
Labels: good first issue, hackathon, hacktoberfest-accepted

#30 Created n_queen_problem.java
  algo/Backtracking/n_queen_problem.java
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest-accepted

#33 Create prim's.py
  algo/prim's/prim's.py
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest2020

#34 Create Heapsort.py
  Sorting/Heapsort.py
Labels: good first issue, hackathon, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#41 Backtracking -N Queens in Python
  algo/Backtracking/n_queen_problem.py
Labels: good first issue, hackathon, hacktoberfest-accepted

#32 Added Quicksort algorithm in Python #29
  Sorting/quick_sort.py
Labels: good first issue, hackathon, hacktoberfest-accepted

#36 Merge Sort added
  Sorting/Merge_Sort.py
Labels: hackathon, hacktoberfest-accepted, hacktoberfest2020

#37 Added CPP code for quick sort for Quick Sort
  Sorting/quicksort.cpp
Labels: good first issue, hackathon, hacktoberfest-accepted, hacktoberfest2020

#39 Use template with functions
  algo/Backtracking/n_queen_problem.cpp
Labels: enhancement, hacktoberfest-accepted, question
